import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Frontend Mentor | QR code component",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-300">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
